feat: new did implementation
KILTprotocol/type-definitions pull request #1
Opened 2021-05-07 13:16 UTC by weichweich

Companion PR for https://github.com/KILTprotocol/mashnet-node/pull/146

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
- [x] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [x] I have documented the changes (where applicable)

2021-05-11 07:29 UTC, Diiaablo95 commented
@rflechtner I tried the types in polkadot-js apps and they are working as expected as in https://github.com/KILTprotocol/mashnet-node/pull/146. Can you please try them out on the SDK and approve the PR if they work? Thanks! 😄

2021-05-11 07:33 UTC, weichweich commented
before this is merged I would also like to have this tested with the polkadot apps. For the mashnet the apps should still use the old types (`types8`), where as they should use the new types (`types9`) for the mashnet-dev or the parachain.

2021-05-11 08:34 UTC, weichweich commented
> Definitions are missing for `DispatchResultWithPostInfo` & `LockedBalance`. Maybe we need to update polkadot.js? Unfortunately this is true for the hosted polkadot apps as well

if we publish a new release of this project, the polkadot apps will be updated when they update the dependencies. which is quite frequently AFAIK

2021-05-11 12:33 UTC, Diiaablo95 commented
Ok `AttestationDetails` is actually my bad. I renamed the struct to avoid conflicts with the pallet name. But we are not using `DelegationNodeId` anywhere anymore, as that has been renamed `DelegationNodeIdOf`.

2021-05-11 12:33 UTC, Diiaablo95 commented
I guess a temporary fix would be to add also `DispatchResultWithPostInfo` and `LockedBalance`?

2021-05-11 13:17 UTC, weichweich commented
> and I found the reason for the delegationNodeId:
> 
> ```
>               {
>                 name: revoke_root,
>                 args: [
>                   {
>                     name: root_id,
>                     type: DelegationNodeId
>                   },
>                   {
>                     name: max_children,
>                     type: u32
>                   }
>                 ],
>                 documentation: [
>                    Revoke a delegation root.,
>                   ,
>                    Revoking a delegation root results in the whole trust hierarchy,
>                    being revoked. Nevertheless, revocation starts from the leave nodes,
>                    upwards, so if the operation ends prematurely because it runs out of,
>                    gas, the delegation state would be consisent as no child would,
>                    survive its parent. As a consequence, if the root node is revoked,,
>                    the whole trust hierarchy is to be considered revoked.,
>                   ,
>                    * origin: the identifier of the revoker,
>                    * root_id: the ID of the delegation root to revoke,
>                    * max_children: the maximum number of nodes descending from the root,
>                      to revoke as a consequence of the root revocation
>                 ]
>               },
> ```
> 
> -> https://github.com/KILTprotocol/mashnet-node/blob/c13e1115d617b84475e44c65d905ac3bde3b612a/pallets/delegation/src/lib.rs#L316

Yes and we have now both `DelegationNodeIdOf` and `DelegationNodeId` which is the same type.

2021-05-11 13:18 UTC, Diiaablo95 commented
I would use `DelegationNodeIdOf` everywhere.

2021-05-12 08:50 UTC, rflechtner requested changes
sorry, I actually do have a concern that I overlooked earlier: can we change every property to use snake case? That's what the sdk expects, as it's a js convention

2021-05-12 08:52 UTC, weichweich commented
> sorry, I actually do have a concern that I overlooked earlier: can we change every property to use snake case? That's what the sdk expects, as it's a js convention

I thought that the custom types expect to have camelCase? That's why i converted everything to camelCase. 😂  😅

2021-05-12 08:53 UTC, rflechtner commented
> > sorry, I actually do have a concern that I overlooked earlier: can we change every property to use snake case? That's what the sdk expects, as it's a js convention
> 
> I thought that the custom types expect to have camelCase? That's why i converted everything to camelCase. 😂 😅

that's what I mean :D we still have some snake case in here, I got confused...

2021-05-12 08:55 UTC, rflechtner commented on src/index.ts
> +    ctype_hash: "CtypeHashOf",
here!

2021-05-12 08:55 UTC, rflechtner commented on src/index.ts
> +    delegation_id: "Option<DelegationNodeIdOf>",
and here!

2021-05-12 08:55 UTC, rflechtner commented on src/index.ts
> +    ctype_hash: "CtypeHashOf",
and here!

2021-05-12 08:55 UTC, rflechtner commented on src/index.ts
> +    root_id: "DelegationNodeIdOf",
and here!

2021-05-12 08:56 UTC, weichweich commented
ah yes! 😁 they need to get converted! 👍🏻

2021-05-18 13:09 UTC, rflechtner approved these changes

2021-05-18 13:11 UTC, merged